language: php

php:
  - 5.3
  - 5.4
  - 5.5

services:
  - memcached # will start memcached

before_install:
  - composer self-update
  - sh -e build/travis/scripts/apt-get.sh
  - sh -e build/travis/scripts/apache2-vhost.sh
  - sh -e build/travis/scripts/apache2-configure.sh

services:
  - memcached # will start memcached

before_script:
  - composer update --dev
  - phpenv config-add build/travis/phpenv/memcached.ini

script:
  - phpunit --configuration phpunit.travis.xml
  
#test
