language: php

php:
  - 5.6

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

services:
  - memcached # will start memcached

before_install:
  - composer self-update
  - sh -e build/travis/scripts/apt-get.sh
  - sh -e build/travis/scripts/apache2-vhost.sh
  - sh -e build/travis/scripts/apache2-configure.sh
  - wget http://localhost -O index.html
  - cat index.html

before_script:
  - composer update --dev
  - phpenv rehash

script:
  - phpunit --configuration phpunit.travis.xml
