name: PHP Composer

on:
  push:
    branches: [ 4.x ]
  pull_request:
    branches: [ 4.x ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0']
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, libsodium, fileinfo
#          coverage: xdebug
#          tools: php-cs-fixer, phpunit

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Start PHP Server
        run: php -S localhost:8100 bin/test-server.php &> /dev/null &

      - name: Run test suite
        run: php vendor/bin/phpunit --configuration phpunit.travis.xml
