name: PHP Composer

on:
  push:
    branches: [ 4.x ]
  pull_request:
    branches: [ 4.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Start PHP Server
        run: php -S localhost:8100 bin/test-server.php &> /dev/null &

      - name: Run test suite
        run: php vendor/bin/phpunit --configuration phpunit.travis.xml
