name: Coding Standards

on: [push, pull_request]

jobs:
  cs:
    runs-on: ubuntu-latest
    env:
      VENDOR: /home/runner/.composer/vendor
    steps:
      - uses: actions/checkout@v2
      # PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: mbstring, intl
      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Prepare LYRA CLI
        run: composer global require lyrasoft/cli --no-progress --no-suggest --ignore-platform-reqs

      - name: Run Sniffer
        run: |
          $VENDOR/bin/lyra sniffer sync
          $VENDOR/bin/phpcs src --standard=$VENDOR/lyrasoft/cli/tmp/development-tools/Sniffer/Windwalker -n --extensions=php

#      - name: Start PHP Server
#        run: php -S localhost:8100 bin/test-server.php &> /dev/null &
#
#      - name: Run test suite
#        run: php vendor/bin/phpunit --configuration phpunit.ci.xml
